name: core
description: Application core
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '<=3.13.9'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  dev_kit:
    git:
      url: https://github.com/StarProxima/dev_kit
      ref: develop

  # Core
  intl: ^0.18.1
  dio: ^5.4.1
  uuid: ^4.3.3
  slang: ^3.29.0
  slang_flutter: ^3.29.0
  shared_preferences: ^2.2.2
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  app_links: ^3.5.0
  auto_route: ^7.8.4
  device_preview: ^1.1.0
  proxima_logger: ^0.7.2
  package_info_plus: ^4.2.0
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.10
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.3.4
  theme_tailor_annotation: ^2.1.0
  auto_exporter_annotation: ^1.0.1


  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fluttertoast: ^8.2.4
  path_provider: ^2.1.2
  mask_text_input_formatter: ^2.9.0
  just_the_tooltip: ^0.0.12

  web_socket_channel: ^2.4.4
  rxdart: ^0.27.7

dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Dev Core
  flutter_lints: ^3.0.1
  lints: ^3.0.0
  custom_lint: ^0.6.0
  riverpod_lint: ^2.3.9
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  riverpod_generator: ^2.3.11
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  # retrofit_generator: ^8.1.0
  auto_route_generator: ^7.3.2
  theme_tailor: ^2.1.0
  auto_exporter: ^3.0.2
  melos: ^4.1.0


flutter_gen:
  output: lib/src/assets/
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true


flutter:
  uses-material-design: true

  assets:
    - assets/