name: admin_app
description: Pixel Battle Admin App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  core:
    path: ../../core

  shared:
    path: ../../shared

  app_runner: ^2.2.2

  dio: ^5.4.1
  http: ^1.1.0

  flutter_native_splash: ^2.3.13
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  melos: ^4.1.0

  flutter_lints: ^3.0.1
  lints: ^3.0.0
  custom_lint: ^0.6.0
  riverpod_lint: ^2.3.9

  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.11

  flutter_launcher_icons: ^0.13.1
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true